fieldLayouts:
  ed0618ae-16b1-40e7-b501-f1c7feb9e0a4:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 1395eacb-28a0-4007-a2d9-822afb0b351b
            warning: null
            width: 100
        name: Content
        uid: c91ac3cd-1c33-4d57-b65a-dfe1ef9b2bdc
fs: main
handle: main
name: Main
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: _transforms
