dateModified: 1696189545
email:
  fromEmail: $CRAFT_EMAIL
  fromName: $CRAFT_SITE_NAME
  replyToEmail: $CRAFT_EMAIL
  template: null
  transportSettings:
    command: '/usr/sbin/sendmail -bs'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  main:
    hasUrls: true
    name: Main
    settings:
      path: upload/main
    type: craft\fs\Local
    url: /upload/main
meta:
  __names__:
    2d0fb778-2d78-49c0-b94d-740200560f8f: Menu # Menu
    2f77b70e-8b00-4e7b-a09c-accad4abad40: Simple # Simple
    4c265acc-11f0-466c-81c1-c43c5cfa3eb9: Entry # Entry
    4d8ac26f-0eed-4e84-8f0f-fb59450142e3: English # English
    5f8ef687-1fd6-4714-9fe5-0e0f7900dcaf: Main # Main
    6bb82573-3aa5-4763-b4ca-603601dce3d2: Global # Global
    6e6e5ab5-ec46-433d-80af-42840709af85: Common # Common
    8ada0e08-6502-434a-b7ff-c252b73ca0df: German # German
    67f102fe-cbe0-438a-8e71-e1f062609695: Entry # Entry
    75d9dd9c-34cd-4041-8eaa-6de7733332b6: 'Custom Title' # Custom Title
    447b1110-2c9a-4975-80e5-fcde89668553: 'Passive Title' # Passive Title
    796b6a3e-2cbd-4359-8c33-3c5411a4112c: 'Custom URL' # Custom URL
    30153e1f-ab40-4497-8d01-3b1425401652: Home # Home
    a252e665-52b5-4799-b56f-cc3bc1eb184f: Home # Home
    ac64e366-584d-4540-bc8e-0cc1a7357ee6: 'Public Schema' # Public Schema
    c3ab0099-2bd0-4fb3-9f99-0b7ef05a796d: 'Custom URL' # Custom URL
    e996c8a5-d46e-498b-90e7-d45110bb6f7a: Extended # Extended
    ebf5391a-5427-4f9f-ad74-cf0abc48ad23: 'Custom Title' # Custom Title
    f4e1bac5-a983-4505-91d2-5a26971ad491: 'Passive Title' # Passive Title
    f5399107-84c7-4af5-8764-8c333d1b9ebc: Dutch # Dutch
    fd05975e-1963-4ddd-8f7b-57678dbe0ac6: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  express-forms:
    edition: lite
    enabled: true
    schemaVersion: 1.0.2
  kint:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: H6A0X6KET0WE87W1H8RCOBUK
    schemaVersion: 2.0.7
  seomatic:
    edition: standard
    enabled: true
    licenseKey: C63OQNOR5ND71J7YP89G1R7F
    schemaVersion: 3.0.12
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: $CRAFT_SITE_NAME
  retryDuration: null
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
